### ISSUE TITLE
[SPIKE] MKDO-Base Workflow Refactor

### ISSUE THREAD

**Issue by mattwatsoncodes** [mkdo/mkdo-base#45]
Initial thoughts around which tools would be best for a MKDO-Base refactor that will make it:

- [ ] Easy to share instances across the team
- [ ] Work cross-platform
- [ ] Not rely on local resources (MySQL, NGINX) being installed
- [ ] Allow quick and easy switching of PHP versions, and other config hotswapping
- [ ] Be easy to use (IE scripted)

**Comment by Vyygir** [comment]
I've put a list of the potential options below with at least a brief description, and a list of points to cover it.

There are obviously a lot more than this but these are the ones that are either popular or actively maintained and meet most of the requirements above.

The most awkward thing to manage, really, is allowing the ability to share instances of each other's builds. Obviously, all of these are containerised or imaged as their own builds, so are effectively a server. But there might be some intracicies that make this not that simple. The environment that seems to have the best support for this, I think, is 10up's but that does has its own caveats as well.

For disabling local resource requirements though, I've not included things like Valet which are fundamentally great, but aren't ideal. In this scenario though, there are additional requirements (e.g. Hyper-V enabled and configured on Windows, which is only available to Windows 10 Pro users, or VirtualBox / any alternatives installed instead).

---

### 10up WP Local Docker

https://github.com/10up/wp-local-docker-v2

- Developed externally and actively maintained
- All environments created, updated, and managed via one interface (CLI)
- Lots of integration with external tools (Memcache, snapshots, etc.)
- Docker based, so definitely cross-platform
- Containerized images rather than locally installed software
- Limited to installing/creating environments via WordPress direct download
- Also requires separate AWS instance for snapshots

Getting this up and runny is pretty simple and straightforward because it’s just a custom Node package for handling WordPress-specific Docker environments. It will do setup and configuration initially, but just from the current WordPress version.

The downside being that if we hit a limitation, it’s not going to be ideal because we have no control over it. There’s also no real in-depth access via this specific interface to doing additional automation (e.g. run setup scripts).

Referring to the docs, this also needs some additional configuration for Windows, so not 100% ideal but it does work as long as the right libs are installed: https://10up.github.io/wp-local-docker-docs/installation/

---

### Docker Compose

https://docs.docker.com/compose/

- No wrappers, just Docker right out of the box (cross-platform, 100%)
- All sites are run independently (via `docker-compose up -d` in the site)
- Access to customise configuration files for each service (Nginx, etc.)
- Again, all sites are containerized
- From experience, Docker is pretty quick
- Definitely requires more management and knowledge
- Not the easiest thing to learn from the start (especially when bringing in Dockerfiles)

This is how I used to run all my sites at my old place, just because it was quicker to run a custom WordPress build locally like this. One command and the environment was up or down, and the files were still on my local system, just moved into a container to be run. We can either pull straight from a WordPress image or build our own specific around the MKDO Base structure -- but it all requires a lot more in-depth coverage than other solutions. It’s a weigh-in between customisation vs. initial ease of use.

---

### VVV

https://varyingvagrantvagrants.org/

- Actively developed and widely used
- Vagrant is as stable as Docker
- An option, but I think you guys have had issues with it in the past?
- Does look to support custom features (e.g. ElasticSearch, Memcache) but needs a lot more work: https://varyingvagrantvagrants.org/docs/en-US/utilities/

I have almost no experience with Vagrant over Docker, but from working with people who’ve previously used it, they made the switch to Docker-Compose after I’d set up the tooling for it because it was faster and more reliable (Win+OSX).

But this does support site templates, so could be far easier to integrate MKDO Base via Git. I’m not 100% on customisation but I think it’s more expandable than 10up WP Docker because of the templating, but it would require a lot more work from the outset.

---

### Local

https://localwp.com/

Local is fine, it’s just another option, but it’s caused me a few issues (constantly wants to change my hosts file, or just crashes randomly, might just be my PC for crashing though). I know Matt uses it as well and, for running sites, it’s worked fine for me. Handles stack configuration nicely. Definitely not customisable and requires some manual file management.

---

### Chassis

https://docs.chassis.io/

I don't know a huge amount about this one but it's been recommended to be before, just generally. Kind of similar to VVV but looks a bit more lightweight on tooling and still customisable.

**Comment by davetgreen** [comment]
## Underlying Stack

**High Level Comments**

- 10UP Docker is good, requires minimal config time, but limits customisation options.
- Docker Compose gives us that customisation, but lose easy snapshots and requires more time.
- VVV is absolutely viable, but we've had bad experiences in the past that may taint it as an option.
- Local is viable but the rest of the team have minimal experience with it.
- Chassis is something we never really tried, but given that Ryan/HM are behind it, it has to be good.

**10UP Docker**
- [ ] Easy to share instances across the team
- [ ] Work cross-platform
- [ ] Not rely on local resources (MySQL, NGINX) being installed
- [ ] Allow quick and easy switching of PHP versions, and other config hotswapping
- [ ] Be easy to use (IE scripted)

**Docker Compose**
- [ ] Easy to share instances across the team
- [ ] Work cross-platform
- [ ] Not rely on local resources (MySQL, NGINX) being installed
- [ ] Allow quick and easy switching of PHP versions, and other config hotswapping
- [ ] Be easy to use (IE scripted)


**VV**
- [ ] Easy to share instances across the team
- [ ] Work cross-platform
- [ ] Not rely on local resources (MySQL, NGINX) being installed
- [ ] Allow quick and easy switching of PHP versions, and other config hotswapping
- [ ] Be easy to use (IE scripted)

**FlyWheel**
- [ ] Easy to share instances across the team
- [ ] Work cross-platform
- [ ] Not rely on local resources (MySQL, NGINX) being installed
- [ ] Allow quick and easy switching of PHP versions, and other config hotswapping
- [ ] Be easy to use (IE scripted)


**Chassis**
- [ ] Easy to share instances across the team
- [ ] Work cross-platform
- [ ] Not rely on local resources (MySQL, NGINX) being installed
- [ ] Allow quick and easy switching of PHP versions, and other config hotswapping
- [ ] Be easy to use (IE scripted)
